export const THEME = {
  "font-family": "Inter, sans-serif",
  "spacing-s": "15px",
  "spacing-m": "25px",
  "spacing-l": "30px",
  "spacing-xl": "50px",
  "color-highlight": "#3861fb",
  "color-neutral-0": "#161616",
  "color-neutral-1": "#58667E",
  "color-neutral-2": "#525252",
  "color-neutral-3": "#EFEFEF",
  "color-neutral-4": "#eff2f5",
  "color-neutral-5": "#fff",
  "color-info": "#5276FF",
  "color-info-light": "#5ABBE426",
  "color-success": "#20BA81",
  "color-warning": "#EDC240",
  "color-error": "#ED4040",
  "border-radius": "8px",
  "font-size-xs": "10px",
  "font-size-s": "12px",
  "font-size-m": "14px",
  "font-size-l": "16px",
  "font-weight-regular": 500,
  "font-weight-semi": 600,
  "font-weight-bold": 700,
  "line-height-xs": "12px",
  "line-height-s": "15px",
  "line-height-m": "17px",
  "line-height-l": "20px",
  "line-height-xl": "24px",
};
