export const apiControlFields: Record<string, React.InputHTMLAttributes<HTMLInputElement>> = {
  from: {
    type: "date",
    required: true,
    placeholder: "From",
    value: "2023-10-14",
  },
  to: {
    type: "date",
    required: true,
    placeholder: "To",
    value: "2023-11-14",
  },
  currentMin: {
    type: "number",
    required: true,
    placeholder: "Current Precip. Min",
    value: 2,
    min: 0,
    step: 0.5,
  },
  currentMax: {
    type: "number",
    required: true,
    placeholder: "Current Precip. Max",
    value: 7,
    min: 0,
    step: 0.5,
  },
  historyAverageMin: {
    type: "number",
    required: true,
    placeholder: "Historical Average Min",
    value: 4,
    min: 0,
    step: 0.5,
  },
  historyAverageMax: {
    type: "number",
    required: true,
    placeholder: "Historical Average Max",
    value: 4.5,
    min: 0,
    step: 0.5,
  },
  shuffleProbability: {
    type: "number",
    required: true,
    placeholder: "Shuffle Probability",
    value: 0.1,
    min: 0,
    max: 1,
    step: 0.1,
  },
  shuffleDistance: {
    type: "number",
    required: true,
    placeholder: "Shuffle Distance",
    value: 0,
    min: 0,
  },
  precision: {
    type: "number",
    required: true,
    placeholder: "Precision",
    value: 0.01,
    step: 0.01,
    min: 0,
  },
};
